#!/bin/bash

#Program to output a system information page

TITLE="System Information Report for $HOSTNAME"
CURRRENT_TIME=$(date +"%x %r %Z")
TIME_STAMP="Genrated $CURRENT_TIME, by $USER"

#Definition of used functions

report_uptime () {
	cat <<- _EOF_
		
		<h2>System uptime</h2>
		<pre>$(uptime)</pre)

		_EOF_
	return
}

report_disk_space () {
	cat <<- _EOF_

		<h2>Disk Space Utitilization</h2>
		<pre>$(df -h)</pre>

		_EOF_
	return
}

report_home_space () {
	cat <<- _EOF_

		<h2>home Space Utitilization</h2>
		<pre>$(du -sh /home/*)</pre>

		_EOF_
	return
}

#End of funciton definitions

cat << _EOF_

<html>
	<head>
		<title>$TITLE</title>
	</head>

	<body>
		<h1>$TITLE</h1>
		<p>$TIME_STAMP</p>
		$(report_uptime)
		$(report_disk_space)
		$(report_home_space)
	</body>
</html>

_EOF_
